name: Docker build

'on':
    pull_request:
    push:
        branches:
          - master
          - develop
          - feature/**

env:
    CMAKE_OPTIONS: -DUserverGrpc_VERSION=1.51.0

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
                submodules: true

          - name: Reuse ccache directory
            uses: actions/cache@v2
            with:
                path: .ccache
                key: 'ccache-dir-${{github.ref}}_run-${{github.run_number}}'
                restore-keys: |
                    ccache-dir-${{github.ref}}_run-
                    ccache-

          - name: Install docker-compose
            run: |
                sudo apt update
                sudo apt install --allow-downgrades -y docker-compose

          - name: Setup ccache
            run: docker-compose run --rm realmedium-sample bash -c 'ccache -M 4.0GB && ccache -s'

          - name: Cmake
            run: make docker-cmake-release

          - name: Build
            run: make docker-build-release

          - name: Run tests
            run: make docker-test-release
